# Generated by Django 2.0.7 on 2020-09-13 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Book Assignment',
                'verbose_name_plural': 'Book Assignments',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Book')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('image', models.ImageField(height_field=100, upload_to='images/', verbose_name='Cover', width_field=100)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_librarian', models.BooleanField(default=True, verbose_name='is_librarian')),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='librarian', to=settings.AUTH_USER_MODEL, verbose_name='Librarian')),
            ],
            options={
                'verbose_name': 'Librarian',
            },
        ),
        migrations.AddField(
            model_name='assignedbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_book', to='books.Book', verbose_name='Issued Book'),
        ),
        migrations.AddField(
            model_name='assignedbooks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to=settings.AUTH_USER_MODEL, verbose_name='Issuer'),
        ),
    ]
