# Generated by Django 2.0.7 on 2020-09-13 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedbooks',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='assignedbooks',
            name='issue_request',
            field=models.CharField(choices=[('i', 'Issued'), ('r', 'Requested')], default='r', max_length=1, verbose_name='Book Assignments Status'),
        ),
        migrations.AddField(
            model_name='assignedbooks',
            name='renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 12, 19, 29, 48140)),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Cover'),
        ),
    ]
